// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: state.proto

package com.intel.missioncontrol.livevideo;

public final class MinAvProtobuf {
  private MinAvProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code MinAv.ReturnStatus}
   */
  public enum ReturnStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>OK = 0;</code>
     */
    OK(0),
    /**
     * <code>ERROR = 1;</code>
     */
    ERROR(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>OK = 0;</code>
     */
    public static final int OK_VALUE = 0;
    /**
     * <code>ERROR = 1;</code>
     */
    public static final int ERROR_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ReturnStatus valueOf(int value) {
      return forNumber(value);
    }

    public static ReturnStatus forNumber(int value) {
      switch (value) {
        case 0: return OK;
        case 1: return ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ReturnStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ReturnStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ReturnStatus>() {
            public ReturnStatus findValueByNumber(int number) {
              return ReturnStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.intel.missioncontrol.livevideo.MinAvProtobuf.getDescriptor().getEnumTypes().get(0);
    }

    private static final ReturnStatus[] VALUES = values();

    public static ReturnStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ReturnStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MinAv.ReturnStatus)
  }

  /**
   * Protobuf enum {@code MinAv.State}
   */
  public enum State
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PROBING = 0;</code>
     */
    PROBING(0),
    /**
     * <code>RUNNING = 1;</code>
     */
    RUNNING(1),
    /**
     * <code>HANGING = 2;</code>
     */
    HANGING(2),
    /**
     * <code>FAILED = 3;</code>
     */
    FAILED(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>PROBING = 0;</code>
     */
    public static final int PROBING_VALUE = 0;
    /**
     * <code>RUNNING = 1;</code>
     */
    public static final int RUNNING_VALUE = 1;
    /**
     * <code>HANGING = 2;</code>
     */
    public static final int HANGING_VALUE = 2;
    /**
     * <code>FAILED = 3;</code>
     */
    public static final int FAILED_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static State valueOf(int value) {
      return forNumber(value);
    }

    public static State forNumber(int value) {
      switch (value) {
        case 0: return PROBING;
        case 1: return RUNNING;
        case 2: return HANGING;
        case 3: return FAILED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<State>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        State> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<State>() {
            public State findValueByNumber(int number) {
              return State.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.intel.missioncontrol.livevideo.MinAvProtobuf.getDescriptor().getEnumTypes().get(1);
    }

    private static final State[] VALUES = values();

    public static State valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private State(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MinAv.State)
  }

  /**
   * Protobuf enum {@code MinAv.SelectStatus}
   */
  public enum SelectStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NO_UPDATE = 0;</code>
     */
    NO_UPDATE(0),
    /**
     * <code>NEW_DATA = 1;</code>
     */
    NEW_DATA(1),
    /**
     * <code>STATE_UPDATE = 2;</code>
     */
    STATE_UPDATE(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NO_UPDATE = 0;</code>
     */
    public static final int NO_UPDATE_VALUE = 0;
    /**
     * <code>NEW_DATA = 1;</code>
     */
    public static final int NEW_DATA_VALUE = 1;
    /**
     * <code>STATE_UPDATE = 2;</code>
     */
    public static final int STATE_UPDATE_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SelectStatus valueOf(int value) {
      return forNumber(value);
    }

    public static SelectStatus forNumber(int value) {
      switch (value) {
        case 0: return NO_UPDATE;
        case 1: return NEW_DATA;
        case 2: return STATE_UPDATE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SelectStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        SelectStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SelectStatus>() {
            public SelectStatus findValueByNumber(int number) {
              return SelectStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.intel.missioncontrol.livevideo.MinAvProtobuf.getDescriptor().getEnumTypes().get(2);
    }

    private static final SelectStatus[] VALUES = values();

    public static SelectStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private SelectStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MinAv.SelectStatus)
  }

  /**
   * Protobuf enum {@code MinAv.LogLevel}
   */
  public enum LogLevel
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>QUIET = 0;</code>
     */
    QUIET(0),
    /**
     * <code>INFO = 1;</code>
     */
    INFO(1),
    /**
     * <code>VERBOSE = 2;</code>
     */
    VERBOSE(2),
    /**
     * <code>DEBUG = 3;</code>
     */
    DEBUG(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>QUIET = 0;</code>
     */
    public static final int QUIET_VALUE = 0;
    /**
     * <code>INFO = 1;</code>
     */
    public static final int INFO_VALUE = 1;
    /**
     * <code>VERBOSE = 2;</code>
     */
    public static final int VERBOSE_VALUE = 2;
    /**
     * <code>DEBUG = 3;</code>
     */
    public static final int DEBUG_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static LogLevel valueOf(int value) {
      return forNumber(value);
    }

    public static LogLevel forNumber(int value) {
      switch (value) {
        case 0: return QUIET;
        case 1: return INFO;
        case 2: return VERBOSE;
        case 3: return DEBUG;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<LogLevel>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        LogLevel> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<LogLevel>() {
            public LogLevel findValueByNumber(int number) {
              return LogLevel.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.intel.missioncontrol.livevideo.MinAvProtobuf.getDescriptor().getEnumTypes().get(3);
    }

    private static final LogLevel[] VALUES = values();

    public static LogLevel valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private LogLevel(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MinAv.LogLevel)
  }

  /**
   * Protobuf enum {@code MinAv.PixelFormat}
   */
  public enum PixelFormat
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>RGB24 = 0;</code>
     */
    RGB24(0),
    /**
     * <code>BGRA = 1;</code>
     */
    BGRA(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>RGB24 = 0;</code>
     */
    public static final int RGB24_VALUE = 0;
    /**
     * <code>BGRA = 1;</code>
     */
    public static final int BGRA_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PixelFormat valueOf(int value) {
      return forNumber(value);
    }

    public static PixelFormat forNumber(int value) {
      switch (value) {
        case 0: return RGB24;
        case 1: return BGRA;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PixelFormat>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PixelFormat> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PixelFormat>() {
            public PixelFormat findValueByNumber(int number) {
              return PixelFormat.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.intel.missioncontrol.livevideo.MinAvProtobuf.getDescriptor().getEnumTypes().get(4);
    }

    private static final PixelFormat[] VALUES = values();

    public static PixelFormat valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PixelFormat(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MinAv.PixelFormat)
  }

  public interface StateDescriptionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MinAv.StateDescription)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 width = 1;</code>
     */
    int getWidth();

    /**
     * <code>int32 height = 2;</code>
     */
    int getHeight();

    /**
     * <code>.MinAv.State state = 3;</code>
     */
    int getStateValue();
    /**
     * <code>.MinAv.State state = 3;</code>
     */
    com.intel.missioncontrol.livevideo.MinAvProtobuf.State getState();

    /**
     * <code>string message = 4;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 4;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code MinAv.StateDescription}
   */
  public  static final class StateDescription extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MinAv.StateDescription)
      StateDescriptionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StateDescription.newBuilder() to construct.
    private StateDescription(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StateDescription() {
      state_ = 0;
      message_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StateDescription();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StateDescription(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              width_ = input.readInt32();
              break;
            }
            case 16: {

              height_ = input.readInt32();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              state_ = rawValue;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.intel.missioncontrol.livevideo.MinAvProtobuf.internal_static_MinAv_StateDescription_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.intel.missioncontrol.livevideo.MinAvProtobuf.internal_static_MinAv_StateDescription_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription.class, com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription.Builder.class);
    }

    public static final int WIDTH_FIELD_NUMBER = 1;
    private int width_;
    /**
     * <code>int32 width = 1;</code>
     */
    public int getWidth() {
      return width_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 2;
    private int height_;
    /**
     * <code>int32 height = 2;</code>
     */
    public int getHeight() {
      return height_;
    }

    public static final int STATE_FIELD_NUMBER = 3;
    private int state_;
    /**
     * <code>.MinAv.State state = 3;</code>
     */
    public int getStateValue() {
      return state_;
    }
    /**
     * <code>.MinAv.State state = 3;</code>
     */
    public com.intel.missioncontrol.livevideo.MinAvProtobuf.State getState() {
      @SuppressWarnings("deprecation")
      com.intel.missioncontrol.livevideo.MinAvProtobuf.State result = com.intel.missioncontrol.livevideo.MinAvProtobuf.State.valueOf(state_);
      return result == null ? com.intel.missioncontrol.livevideo.MinAvProtobuf.State.UNRECOGNIZED : result;
    }

    public static final int MESSAGE_FIELD_NUMBER = 4;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 4;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (width_ != 0) {
        output.writeInt32(1, width_);
      }
      if (height_ != 0) {
        output.writeInt32(2, height_);
      }
      if (state_ != com.intel.missioncontrol.livevideo.MinAvProtobuf.State.PROBING.getNumber()) {
        output.writeEnum(3, state_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (width_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, width_);
      }
      if (height_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, height_);
      }
      if (state_ != com.intel.missioncontrol.livevideo.MinAvProtobuf.State.PROBING.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, state_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription)) {
        return super.equals(obj);
      }
      com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription other = (com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription) obj;

      if (getWidth()
          != other.getWidth()) return false;
      if (getHeight()
          != other.getHeight()) return false;
      if (state_ != other.state_) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WIDTH_FIELD_NUMBER;
      hash = (53 * hash) + getWidth();
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getHeight();
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + state_;
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MinAv.StateDescription}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MinAv.StateDescription)
        com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescriptionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.intel.missioncontrol.livevideo.MinAvProtobuf.internal_static_MinAv_StateDescription_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.intel.missioncontrol.livevideo.MinAvProtobuf.internal_static_MinAv_StateDescription_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription.class, com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription.Builder.class);
      }

      // Construct using com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        width_ = 0;

        height_ = 0;

        state_ = 0;

        message_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.intel.missioncontrol.livevideo.MinAvProtobuf.internal_static_MinAv_StateDescription_descriptor;
      }

      @java.lang.Override
      public com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription getDefaultInstanceForType() {
        return com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription.getDefaultInstance();
      }

      @java.lang.Override
      public com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription build() {
        com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription buildPartial() {
        com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription result = new com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription(this);
        result.width_ = width_;
        result.height_ = height_;
        result.state_ = state_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription) {
          return mergeFrom((com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription other) {
        if (other == com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription.getDefaultInstance()) return this;
        if (other.getWidth() != 0) {
          setWidth(other.getWidth());
        }
        if (other.getHeight() != 0) {
          setHeight(other.getHeight());
        }
        if (other.state_ != 0) {
          setStateValue(other.getStateValue());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int width_ ;
      /**
       * <code>int32 width = 1;</code>
       */
      public int getWidth() {
        return width_;
      }
      /**
       * <code>int32 width = 1;</code>
       */
      public Builder setWidth(int value) {
        
        width_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 width = 1;</code>
       */
      public Builder clearWidth() {
        
        width_ = 0;
        onChanged();
        return this;
      }

      private int height_ ;
      /**
       * <code>int32 height = 2;</code>
       */
      public int getHeight() {
        return height_;
      }
      /**
       * <code>int32 height = 2;</code>
       */
      public Builder setHeight(int value) {
        
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 height = 2;</code>
       */
      public Builder clearHeight() {
        
        height_ = 0;
        onChanged();
        return this;
      }

      private int state_ = 0;
      /**
       * <code>.MinAv.State state = 3;</code>
       */
      public int getStateValue() {
        return state_;
      }
      /**
       * <code>.MinAv.State state = 3;</code>
       */
      public Builder setStateValue(int value) {
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.MinAv.State state = 3;</code>
       */
      public com.intel.missioncontrol.livevideo.MinAvProtobuf.State getState() {
        @SuppressWarnings("deprecation")
        com.intel.missioncontrol.livevideo.MinAvProtobuf.State result = com.intel.missioncontrol.livevideo.MinAvProtobuf.State.valueOf(state_);
        return result == null ? com.intel.missioncontrol.livevideo.MinAvProtobuf.State.UNRECOGNIZED : result;
      }
      /**
       * <code>.MinAv.State state = 3;</code>
       */
      public Builder setState(com.intel.missioncontrol.livevideo.MinAvProtobuf.State value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        state_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.MinAv.State state = 3;</code>
       */
      public Builder clearState() {
        
        state_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 4;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 4;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 4;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 4;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MinAv.StateDescription)
    }

    // @@protoc_insertion_point(class_scope:MinAv.StateDescription)
    private static final com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription();
    }

    public static com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StateDescription>
        PARSER = new com.google.protobuf.AbstractParser<StateDescription>() {
      @java.lang.Override
      public StateDescription parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StateDescription(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StateDescription> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StateDescription> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.intel.missioncontrol.livevideo.MinAvProtobuf.StateDescription getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MinAv_StateDescription_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MinAv_StateDescription_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013state.proto\022\005MinAv\"_\n\020StateDescription" +
      "\022\r\n\005width\030\001 \001(\005\022\016\n\006height\030\002 \001(\005\022\033\n\005state" +
      "\030\003 \001(\0162\014.MinAv.State\022\017\n\007message\030\004 \001(\t*!\n" +
      "\014ReturnStatus\022\006\n\002OK\020\000\022\t\n\005ERROR\020\001*:\n\005Stat" +
      "e\022\013\n\007PROBING\020\000\022\013\n\007RUNNING\020\001\022\013\n\007HANGING\020\002" +
      "\022\n\n\006FAILED\020\003*=\n\014SelectStatus\022\r\n\tNO_UPDAT" +
      "E\020\000\022\014\n\010NEW_DATA\020\001\022\020\n\014STATE_UPDATE\020\002*7\n\010L" +
      "ogLevel\022\t\n\005QUIET\020\000\022\010\n\004INFO\020\001\022\013\n\007VERBOSE\020" +
      "\002\022\t\n\005DEBUG\020\003*\"\n\013PixelFormat\022\t\n\005RGB24\020\000\022\010" +
      "\n\004BGRA\020\001B3\n\"com.intel.missioncontrol.liv" +
      "evideoB\rMinAvProtobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MinAv_StateDescription_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MinAv_StateDescription_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MinAv_StateDescription_descriptor,
        new java.lang.String[] { "Width", "Height", "State", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
