/**
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
// This file was generated by a tool. Do not edit.
//
package org.asyncfx.beans.property;

import javafx.beans.InvalidationListener;
import javafx.beans.property.${boxedType}Property;
import javafx.beans.property.Property;
import javafx.beans.value.ChangeListener;
import javafx.beans.value.ObservableValue;
import org.asyncfx.beans.binding.ProxyExpressionHelper;

#set($isNumberType = $boxedType == "Integer" || $boxedType == "Long" || $boxedType == "Float" || $boxedType == "Double")

class ${boxedType}PropertyProxy$!{genericType} extends ${boxedType}Property$!{genericType} {

    @SuppressWarnings({"FieldCanBeLocal", "unused"})
    private final PropertyPath.PropertyPathSegment endpoint;
    private final $primType fallbackValue;
    private ObservableValue<? extends $numberType> observable;
    private ProxyExpressionHelper<$numberType> helper;
    private Property<$numberType> peer;

    ${boxedType}PropertyProxy(PropertyPath.PropertyPathSegment endpoint, $primType fallbackValue) {
        this.endpoint = endpoint;
        this.fallbackValue = fallbackValue;
    }

    void setPeer(Property<$numberType> peer) {
        if (observable != null) {
            if (this.peer != null) {
                this.peer.unbind();
            }

            peer.bind(observable);
        }

        this.peer = peer;

        ProxyExpressionHelper.setPeer(helper, peer);
    }

    @Override
    public void bind(ObservableValue<? extends $numberType> observable) {
        this.observable = observable;

        if (peer != null) {
            peer.bind(observable);
        }
    }

    @Override
    public void unbind() {
        observable = null;

        if (peer != null) {
            peer.unbind();
        }
    }

    @Override
    public boolean isBound() {
        return observable != null;
    }

    @Override
    public Object getBean() {
        return peer != null ? peer.getBean() : null;
    }

    @Override
    public String getName() {
        return peer != null ? peer.getName() : null;
    }

    @Override
    public $primType get() {
        if (peer == null) {
            return fallbackValue;
        }

#if($boxedType == "Boolean")
        Boolean value = peer.getValue();
        return value != null ? value : false;
#elseif($isNumberType)
        Number value = peer.getValue();
        return value != null ? value.${primType}Value() : 0;
#else
        return peer.getValue();
#end
    }

    @Override
    public void addListener(ChangeListener<? super $numberType> changeListener) {
        helper = ProxyExpressionHelper.addListener(helper, this, peer, changeListener);
    }

    @Override
    public void removeListener(ChangeListener<? super $numberType> changeListener) {
        helper = ProxyExpressionHelper.removeListener(helper, changeListener);
    }

    @Override
    public void addListener(InvalidationListener invalidationListener) {
        helper = ProxyExpressionHelper.addListener(helper, this, peer, invalidationListener);
    }

    @Override
    public void removeListener(InvalidationListener invalidationListener) {
        helper = ProxyExpressionHelper.removeListener(helper, invalidationListener);
    }

    @Override
    public void set($primType value) {
        if (peer != null) {
            peer.setValue(value);
        }
    }

    @Override
    public synchronized String toString() {
        Object bean = this.getBean();
        String name = this.getName();
        StringBuilder stringBuilder = new StringBuilder(getClass().getSimpleName());
        stringBuilder.append(" [");
        if (bean != null) {
            stringBuilder.append("bean: ").append(bean).append(", ");
        }

        if (name != null && !name.equals("")) {
            stringBuilder.append("name: ").append(name).append(", ");
        }

        if (peer == null) {
            stringBuilder.append("unresolved, ");
        }

        stringBuilder.append("value: ").append(this.get()).append("]");
        return stringBuilder.toString();
    }

}
