/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace LizardTech.LidarSDK {

public enum DataType {
  DATATYPE_INVALID = 0x0000,
  DATATYPE_UINT8 = 0x0100,
  DATATYPE_SINT8 = 0x0101,
  DATATYPE_UINT16 = 0x0200,
  DATATYPE_SINT16 = 0x0201,
  DATATYPE_UINT32 = 0x0400,
  DATATYPE_SINT32 = 0x0401,
  DATATYPE_UINT64 = 0x0800,
  DATATYPE_SINT64 = 0x0801,
  DATATYPE_FLOAT32 = 0x0403,
  DATATYPE_FLOAT64 = 0x0803
}

}
