/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace LizardTech.LidarSDK {

using System;
using System.Runtime.InteropServices;

public class LidarDSDK {
  public static readonly string CHANNEL_NAME_X = LidarDSDKPINVOKE.CHANNEL_NAME_X_get();
  public static readonly string CHANNEL_NAME_Y = LidarDSDKPINVOKE.CHANNEL_NAME_Y_get();
  public static readonly string CHANNEL_NAME_Z = LidarDSDKPINVOKE.CHANNEL_NAME_Z_get();
  public static readonly string CHANNEL_NAME_Intensity = LidarDSDKPINVOKE.CHANNEL_NAME_Intensity_get();
  public static readonly string CHANNEL_NAME_ReturnNum = LidarDSDKPINVOKE.CHANNEL_NAME_ReturnNum_get();
  public static readonly string CHANNEL_NAME_NumReturns = LidarDSDKPINVOKE.CHANNEL_NAME_NumReturns_get();
  public static readonly string CHANNEL_NAME_ScanDir = LidarDSDKPINVOKE.CHANNEL_NAME_ScanDir_get();
  public static readonly string CHANNEL_NAME_EdgeFlightLine = LidarDSDKPINVOKE.CHANNEL_NAME_EdgeFlightLine_get();
  public static readonly string CHANNEL_NAME_ScannerChannel = LidarDSDKPINVOKE.CHANNEL_NAME_ScannerChannel_get();
  public static readonly string CHANNEL_NAME_ClassId = LidarDSDKPINVOKE.CHANNEL_NAME_ClassId_get();
  public static readonly string CHANNEL_NAME_ClassFlags = LidarDSDKPINVOKE.CHANNEL_NAME_ClassFlags_get();
  public static readonly string CHANNEL_NAME_ScanAngle = LidarDSDKPINVOKE.CHANNEL_NAME_ScanAngle_get();
  public static readonly string CHANNEL_NAME_UserData = LidarDSDKPINVOKE.CHANNEL_NAME_UserData_get();
  public static readonly string CHANNEL_NAME_SourceId = LidarDSDKPINVOKE.CHANNEL_NAME_SourceId_get();
  public static readonly string CHANNEL_NAME_GPSTime_Week = LidarDSDKPINVOKE.CHANNEL_NAME_GPSTime_Week_get();
  public static readonly string CHANNEL_NAME_GPSTime_Adjusted = LidarDSDKPINVOKE.CHANNEL_NAME_GPSTime_Adjusted_get();
  public static readonly string CHANNEL_NAME_Red = LidarDSDKPINVOKE.CHANNEL_NAME_Red_get();
  public static readonly string CHANNEL_NAME_Green = LidarDSDKPINVOKE.CHANNEL_NAME_Green_get();
  public static readonly string CHANNEL_NAME_Blue = LidarDSDKPINVOKE.CHANNEL_NAME_Blue_get();
  public static readonly string CHANNEL_NAME_NearInfrared = LidarDSDKPINVOKE.CHANNEL_NAME_NearInfrared_get();
  public static readonly string CHANNEL_NAME_Skip = LidarDSDKPINVOKE.CHANNEL_NAME_Skip_get();
  public static readonly string METADATA_KEY_FileSourceID = LidarDSDKPINVOKE.METADATA_KEY_FileSourceID_get();
  public static readonly string METADATA_KEY_ProjectID = LidarDSDKPINVOKE.METADATA_KEY_ProjectID_get();
  public static readonly string METADATA_KEY_SystemID = LidarDSDKPINVOKE.METADATA_KEY_SystemID_get();
  public static readonly string METADATA_KEY_GeneratingSoftware = LidarDSDKPINVOKE.METADATA_KEY_GeneratingSoftware_get();
  public static readonly string METADATA_KEY_FileCreationDate = LidarDSDKPINVOKE.METADATA_KEY_FileCreationDate_get();
  public static readonly string METADATA_KEY_PointRecordsByReturnCount = LidarDSDKPINVOKE.METADATA_KEY_PointRecordsByReturnCount_get();
  public static readonly string METADATA_KEY_PreCompressionPointCount = LidarDSDKPINVOKE.METADATA_KEY_PreCompressionPointCount_get();
  public static readonly string METADATA_KEY_LASBBox = LidarDSDKPINVOKE.METADATA_KEY_LASBBox_get();
}

}
