/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace LizardTech.LidarSDK {

public enum MetadataDataType {
  METADATA_DATATYPE_INVALID = 0,
  METADATA_DATATYPE_STRING = 1,
  METADATA_DATATYPE_BLOB = 2,
  METADATA_DATATYPE_REAL_ARRAY = 3
}

}
