package com.intel.dronekitsample.anp;

import com.google.gson.annotations.SerializedName;
import com.o3dr.services.android.lib.coordinate.LatLongAlt;

import java.util.Collections;
import java.util.List;

/**
 * class used with Gson to deserialize JSON from ANP file generated by IMC for
 * Intel Cockpit. Classes mirror structure of "project.json"
 */
public class AnpMission {
    public Model model;
    public String heightReference;
    public String description;
    public Takeoff takeoff;

    public List<Task> getWaypoints() {
        if (model == null || model.tasks == null) return Collections.emptyList();
        return model.tasks;
    }

    public static class Model {
        List<Task> tasks;
    }

    public static class Takeoff {
        LatLongAlt position;

        @SerializedName("tolerance radius")
        double tolerance_radius;
    }

    public interface Action {
        String NONE = "None";
        String TRIGGER = "Trigger";
    }

    public static class Task {
        public String action;

        public int actionDelay;
        public int postActionDelay;

        double desiredAcceleration;
        public double maxSpeed;

        @SerializedName("class")
        String className;
        public LatLongAlt position;
        public Orientation orientation;
        public String type;
    }

    public static class Orientation {
        public double pitch;
        public double roll;
        public double yaw;
    }
}
